### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by AndreLaranjeira** [Hugo-NF/farmacia-de-bolso#22]
Verificar o website e agregar tudo nos slides.

Importante: O item 'k' 2 vídeos com uso de think aloud será feito (#21).

**Comment by 01oseluiz** [comment]
link para edição no canva (é preciso registo p/ acesso):
https://www.canva.com/design/DAEdGa42yJc/share/preview?token=YPX6JuZ2M0wa1OG9OaXgnQ&role=EDITOR&utm_content=DAEdGa42yJc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
